name: tut_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5


  retrofit: ^4.0.1
  analyzer: ^5.13.0
  dio: ^5.2.1+1
  json_serializable: ^6.6.2
  retrofit_generator: ^7.0.8
  build_runner: ^2.3.3

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.0
  freezed: ^2.4.1
  get_it: ^7.6.0
  lottie: ^2.3.2
  country_code_picker: ^3.0.0
  image_picker: ^1.0.1
  rxdart: ^0.27.7
  carousel_slider: ^4.2.1
  easy_localization: ^3.0.2
  flutter_phoenix: ^1.1.1





dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
     - assets/images/splash_logo.png
     - assets/images/camera.png
     - assets/images/onboarding_logo1.svg
     - assets/images/onboarding_logo2.svg
     - assets/images/onboarding_logo3.svg
     - assets/images/onboarding_logo4.svg
     - assets/images/solid_circle_ic.svg
     - assets/images/right_arrow_ic.svg
     - assets/images/left_arrow_ic.svg
     - assets/images/hollow_circle_ic.svg
     - assets/json/Loading.json
     - assets/json/Error.json
     - assets/json/Empty.json
     - assets/images/settings.svg
     - assets/images/contact_us.svg
     - assets/images/invite_friends.svg
     - assets/images/logout.svg
     - assets/images/right.svg
     - assets/translations/ar-SA.json
     - assets/translations/en-US.json


  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat-Bold.ttf
           weight: 700
         - asset: assets/fonts/Montserrat-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Montserrat-Medium.ttf
           weight: 500
         - asset: assets/fonts/Montserrat-Regular.ttf
           weight: 400
         - asset: assets/fonts/Montserrat-Light.ttf
           weight: 300








